version: '3.8'
services:
  frontend:
    build:
      dockerfile: ./frontend/frontend2.Dockerfile
      context: .
    image: mars-frontend-prod
    ports: 
      - '3000:3000'
    restart: always
    volumes:
      - local
#    depends_on:
#      - backend
networks:
  marsnetwork:
    driver: bridge
volumes:
  db:
    driver: local