version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./database/tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  frontend:
    build:
      dockerfile: ./frontend/frontend2.Dockerfile
      context: .
    image: mars-frontend-prod
    ports: 
      - '3000:3000'
    restart: always
    volumes:
      - local
volumes:
  db:
    driver: local